### PR TITLE
Init GitHub Actions workflow for brok URL and pre-commit tests

### LINKED ISSUE #159: Have a pre-commit check
I recently opened a PR to the incubator and @Loquacity discovered my commit had some "smart apostrophes" in it. One possible workaround for catching this would be to add a pre-commit checker for PRs. However, this is a little tricky to set up and it's tricky to learn how to set it up on your local preview if you're not familiar with that convention.

### PR DESCRIPTION
**Pull request by ScriptAutomate**
> __ALL Pull-Requests require an associated [Issue](https://github.com/thegooddocsproject/templates/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) as documented in [How to contribute](https://github.com/thegooddocsproject/templates/blob/master/CONTRIBUTING.md#contributing).__

## Purpose / why

Fixes #159

## What changes were made?

- Added baseline pre-commit config
- Added `.brok-ignore-links` config file with example URL
- Added baseline GitHub Actions testing
  - Runs everything in the `.pre-commit-config.yaml`
  - Runs `brok` for URL tests against all `*.md` files in repo

## Verification

View an example of this running on my preview branch, where I also discovered a broken link that is being fixed in this PR because of it:
- https://github.com/ScriptAutomate/templates/runs/1544485128?check_suite_focus=true

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Are issues linked correctly?
* [ ] Is this PR labeled correctly?
* [ ] If template updates: do they align with [developers.google.com/style/](https://developers.google.com/style/)?
* [ ] Did the PR receive at least one :+1: and no :-1: from core-maintainers?
* [ ] On merging, did you complete the merge using [keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue)?
* [ ] On merging, did you add any applicable notes to a [draft release](https://github.com/thegooddocsproject/templates/releases) and link to this PR?

### CODE REVIEW

**Comment by ScriptAutomate** [comment]
If `pre-commit` is a tool we'd want to use, I can also extend this PR to include directions on using `pre-commit` itself, for contributors.

**Comment by mgan59** [comment]
@ScriptAutomate I moved the repository to `main` and changed the base branch on this PR.  If you end up pushing additional changes be aware as it may require a `rebase`.

**Comment by barbaricyawps** [comment]
@ScriptAutomate , I really want to merge this PR in (and apologies for the delay reviewing it), but we've made changes to the PR template since you submitted this PR. You'll probably have to rebase and fetch the updated PR template. Once those changes are in, I'd love to merge this in.

**Review by barbaricyawps — CHANGES_REQUESTED** [review]
Can you remove the changes to the PR template?

**Comment by barbaricyawps** [comment]
@ScriptAutomate , I think I'm going to close this PR for now. We're planning a GitLab migration, so I'd like to close out any PRs that don't look like they might not make it in by that time.

**Pull request closed without merging**
