### PR TITLE
Expanded on previous CONTRIBUTING guide

### PR DESCRIPTION
**Pull request by Francesco-Lanciana**
* Added a how to contribute section.
* Added more details about the email list
* Reworded certain sections (e.g. Before you contribute)
* Changed some of the titles
* Renamed the file so it's easier to notice

@camerons Do we still need contributors to agree to the Developer Certificate of Origin? What is the purpose of this?

### CODE REVIEW

**Comment by camerons** [comment]
Thanks @Francesco-Lanciana. I've been working in parallel with you, and so we have overlapped on a number of items you have picked up on, which I suggest we should harmonise. (I suspect it might be easier to create a new pull request, after discussing in our weekly meeting).

* I like the topics that you are covering in the "How to Contribute" section. I think we should expand on it.. In particular:
** Language used assumes the reader understands git, using terms "fork", "PR" etc. I expect that most contributors will start with very limited git expertise. So we should expand this out.
** And if we are to expand this out, it probably should go into a separate page. (I'm thinking it should go into our governance docs, which I'm proposing we expand upon.)

* Re email list, I've just created a page https://thegooddocsproject.dev/contact.html which contains these details, so I don't think we need to duplicate this info here now.

* I like what you have in the "Before you contribute", but reckon it fits better in your "How to Contribute" section (which I'm suggesting we move to another page).

* I'm mildly against renaming contribute.md to CONTRIBUTING.md because I like keeping filenames consistent, but am ready to be convinced otherwise if you can point to a convention that we follow. (Note that we'd need to change the nav page too so that the toolbar points to the new page.) If you are creating a new pull request, then please do the file rename in a separate pull request, so I can easily see the changes to the file. (At the moment, we can't easily see what has changed from the git pull request).

**Comment by Francesco-Lanciana** [comment]
Ahh I see, happy to discuss at the meeting who should do what. I agree on expanding it out, that's a good idea. I don't think it should go into a seperate page though, why make them read two pages when they could just read one? Unless we have an expanded version on another page and the collapsed version on the Contributing page?

As for the contacts I don't think it hurts to have links in more than one place for convenience sake. Having said that I'm not too fussed if you just want to consolidate them in one spot.

Happy to do another pull request just with the changes. I had changed the file name because we were already using uppercase for other meta files (DCO/LICENSE) and that was just the convention I had generally seen used. Now that I think about it I don't really have a good reason so happy to go with what you had. Good catch on the nave page link, hadn't realised changing the filename also changed the link (funny that the link isn't an id instead of the name :/)

**Comment by Francesco-Lanciana** [comment]
Ahh I see, happy to discuss at the meeting who should do what. I agree on expanding it out, that's a good idea. I don't think it should go into a seperate page though, why make them read two pages when they could just read one? Unless we have an expanded version on another page and the collapsed version on the Contributing page?

As for the contacts I don't think it hurts to have links in more than one place for convenience sake. Having said that I'm not too fussed if you just want to consolidate them in one spot.

Happy to do another pull request just with the changes. I had changed the file name because we were already using uppercase for other meta files (DCO/LICENSE) and that was just the convention I had generally seen used. Now that I think about it I don't really have a good reason so happy to go with what you had. Good catch on the nave page link, hadn't realised changing the filename also changed the link (funny that the link isn't an id instead of the name :/)

**Comment by jaredmorgs** [comment]
CONTRIBUTING.MD is the standard for

**Pull request closed without merging**
