### PR TITLE
Added Proto Personas

### PR DESCRIPTION
**Pull request by totewar**
- added an about page
- added proto-personas for developers, non-native english humans, newbie wordsmiths and leaders

### CODE REVIEW

**Comment by totewar** [comment]
This is my commit message

Signed-off-by: Sanket Totewar <sanket@totewar.com>

**Comment by camerons** [comment]
As mentioned in weekly meeting today:
* I think discussing personas is a good idea, but material so far doesn't look polished or well researched.
* Our material should be a summary of international best practices.
* We should start by researching to find best practices in the world.
* We should invite the best people in the world to review our best practices, (and not consider our material ready until we have got such review.)
* People using our material should have confidence that our material is best practice, which they can see from our references.
* Our material that is included in templates should be distilled down to bare essentials for our target audience - we don't want our audience to have to read all the research, just what they need to know.

**Comment by emckean** [comment]
sorry not to make the meeting today, am in a completely different time zone
this week (UK).

I 💯 agree with these points, please take this as my hearty +1!

Erin

**Comment by cwcromwell** [comment]
Personas are a great idea. 

I would suggest changes from what I see in these examples. 

* I would place less emphasis on the fear of writing. Some developers may have a fear of writing, and we can help them to get started. These templates help anyone who wants to write documentation, however, including skilled technical writers. They're probably more interested in talking about templates than anyone. (They're not only for beginners or the fearful.)
* I wouldn't say that we help developers understand what contents their documentation needs so that they can coach others (as one of these personas states). It's more like we help them understand so they can write better documentation. 
* We need a persona for the technical writer. Technical writers need a model they can use to verify the the documentation is complete when they join a new project; and for reference when they start a new project..

**Comment by mgan59** [comment]
JobStory2

**Comment by emckean** [comment]
after discussion on 5/20 we're going to close this and create an issue for further discussion: https://github.com/thegooddocsproject/templates/issues/133

**Pull request closed without merging**
