### PR TITLE
readme edits to C/T/R

### PR DESCRIPTION
**Pull request by Loquacity**
Addresses: https://github.com/thegooddocsproject/templates/issues/73
Additionally, frames the C/T/R discussion in terms of the information seeking behaviour (learning/doing/fact-checking).
Also, removed some of the word/phrases that my current linters didn't like.

Question for maintainers: I noticed the use of en_GB spelling in this doc, and couldn't find guidance on dialect. Is there a preference?

### CODE REVIEW

**Comment by Loquacity** [comment]
> Excellent revisions, Lana. I like the parallelism in the revised sections.

Thanks.

> 
> I believe we have shifted to en_US in line with the Google Developer Style Guide.

Updated :)

**Comment by Loquacity** [comment]
Thanks for the review, Jared. Are you able to add more reviewers to the list? I don't have perms.

**Comment by Loquacity** [comment]
Resolved conflicts.

**Comment by Loquacity** [comment]
> Thanks for the review, Jared. Are you able to add more reviewers to the list? I don't have perms.

I have perms now, so have added the suggested reviewers.

**Comment by aidanatwork** [comment]
Given the approval from Jared and thumbs up from me and Loquacity, I'm merging this PR.

**Pull request merged**
