### PR TITLE
Add more detailed contributing information

### PR DESCRIPTION
**Pull request by jaredmorgs**
Add a basic procedure about how to contribute a fix that isn't a typo.

This enhancement was identified in the slack #general room.

### CODE REVIEW

**Comment by mgan59** [comment]
👍 Looks good!

**Comment by camerons** [comment]
I'm -0 (non blocking vote against).
I think the idea is right, but some more is required.
* We are introducing a conflict in advice further in the doc. (Update suggests notifying slack, below it suggests email list). 
* Further down it talks about issue tracking, and the inserted section is also talking about issue tracking.
* In our weekly meeting one of the main issues Max identified is permissions granted to approve pull requests. I think it is worth noting that this is going to become more rigorous over time. Currently we trust of Project Steering Committee tech writers to make a call on accept/reject. But we shouldn't accept our own pull requests. 

Separate to this pull request, we should consider grouping this document in the same repository as our other governance docs: E.g.: https://github.com/thegooddocsproject/governance/blob/master/ProjectSteeringCommittee.md

**Comment by jaredmorgs** [comment]
@camerons I think if we get this PR applied then we can take a closer look at the other sections of this file and clean them up a bit.

For now, lets "iterate, not gold plate" and get this contributing info in.

**Comment by jaredmorgs** [comment]
@flicstar or @camerons can you Squash and Merge if you are OK with the closing comment I made please?

**Comment by camerons** [comment]
I'm about to merge this pull request in line with Jared's suggestion of iterate rather than gold plate.

**Pull request merged**
