### PR TITLE
WIP: Create template-explanation.md

### PR DESCRIPTION
**Pull request by viraji**
In the process of updating the Explanation template. Starting off by converting the existing template-explanation.adoc file to .md. Adding new template-explanation.md file. 

# Template quality checklist

This quality checklist will eventually become a pull request template that every contributor needs to add to pull requests against the `templates` repository.

# Pull request summary

Upgrading old  Explanation/Concepts template. This is still WIP, the content needs to be added/changed. 

## Template contributor checklist

IMPORTANT: The next three sections in this checklist should be filled out by the template contributor at the time they submit this request.

NOTE: Pull requests can only be merged when all boxes are checked.

### Which issue does this pull request fix or reference? (no created issue as far as I am aware.)

This pull request:

- Resolves: {Choose this option if this PR will close the issue and link to issue}
- Relates to: Upgrading old templates.
{Choose this option if this PR only references an issue for context but does not fully resolve it}

### Procedural requirements

- [ ] The template contributor participated in a template working group to create this template.
- [ ] This template was submitted to the community for feedback.
- [ ] A template mentor approved this template set to move to the pull request phase.

### Template set requirements

- [ ] Template file is present.
- [ ] Template guide is present.
- [ ] Template deep dive is present (optional).
- [ ] Template example is present (optional).
- [ ] If the optional template example is not present, open a new issue to track this task in the [Chronologue repository](https://github.com/thegooddocsproject/chronologue/issues), then include the link here.

## Template pull request reviewer checklist

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized Good Docs Project pull request reviewers. If you are the individual template contributor, do not fill out the rest of the fields or check the boxes.

NOTE: Pull requests can only be merged when all boxes are checked.

### Mechanics and formatting requirements - PULL REQUEST REVIEWER ONLY

- [ ] Check rendered Markdown output to ensure it renders correctly.
- [ ] Review the template set to ensure all documents follow the template markdown style guide.
- [ ] The template set is free from grammar errors and typos.

### Overall usability - PULL REQUEST REVIEWER ONLY

- [ ] The scope of the template set is appropriate, meaning it is not too simple or overly complex (i.e. it needs to be expanded or broken into multiple smaller templates).
- [ ] The template is complete and comprehensive.
- [ ] The template set is well-organized and the contents flow in a logical order.
- [ ] The template is well-written and clear.
- [ ] The template set provides sufficient guidance about how to fill it in and implement the template in a documentation project.

### Template file requirements - PULL REQUEST REVIEWER ONLY

- [ ] Check rendered Markdown output to ensure it renders correctly and follows the template markdown style guide.
- [ ] The template title is present and is an H1.
- [ ] The template includes an introductory comment mentioning the other template resources (such as the guide).
- [ ] Embedded writing tips are formatted with {curly brackets}.
- [ ] The template is free from grammar errors and typos.
- [ ] The scope of the template is appropriate, meaning it is not too simple or overly complex (i.e. it needs to be expanded or broken into multiple smaller templates).
- [ ] The template is complete and comprehensive.
- [ ] The template is well-organized and the contents flow in a logical order.
- [ ] The template is well-written and clear.

### Template guide requirements - PULL REQUEST REVIEWER ONLY

- [ ] Check rendered Markdown output to ensure it renders correctly and follows the template markdown style guide.
- [ ] The template guide title is present and is an H1.
- [ ] The template includes an introductory comment pointing them to other template resources.
- [ ] Embedded writing tips are formatted with {curly brackets}.
- [ ] The template guide is free from grammar errors and typos.
- [ ] The template guide includes a "Why do I need this type of document?" section.
- [ ] The template guide includes a "Contents of this template" section.
- [ ] The contents listed in the "Contents of this template" section mirror the sections in the raw template.
- [ ] The template guide includes an implementation checklist (optional).
- [ ] The template guide includes additional resources (optional).
- [ ] The template guide is well-organized and the contents flow in a logical order.
- [ ] The template guide is well-written, clear, and provides sound advice to template users.

### Deep dive requirements (optional) - PULL REQUEST REVIEWER ONLY

- [ ] Check rendered Markdown output to ensure it renders correctly and follows the template markdown style guide.
- [ ] The deep drive title is present and is an H1.
- [ ] The deep dive guide provides helpful advice about necessary requirements for writing this type of documentation.
- [ ] The template set is well-organized and the contents flow in a logical order.
- [ ] The template is well-written and clear.

### Template example requirements (optional) - PULL REQUEST REVIEWER ONLY

- [ ] Check rendered Markdown output to ensure it renders correctly and follows the template markdown style guide.
- [ ] The template example provided is well-written and provides a clear example of how to use the template.

### CODE REVIEW

**Comment by barbaricyawps** [comment]
@viraji , are you hoping for some reviews from community members or are you still working on this template and not quite ready for review?

**Comment by viraji** [comment]
> @viraji , are you hoping for some reviews from community members or are you still working on this template and not quite ready for review?

Hi Alyssa, this is not yet ready for review - I'm being hindered by infrastructure issues at my end (we have daily imposed power cuts in Sri Lanka these days and I've had to work around that, trying to do all work during the hours we have power!). But I am working on this, just slower than before. I shall update my EMEA/APAC team tomorrow at the meeting of the progress. Thanks for checking.

**Comment by barbaricyawps** [comment]
@viraji , thank you for your reply. Is it okay if I temporarily mark this as WIP (work in progress) in the title? I'll make those edits just so that we know.

FYI, there's a possibility that if this doesn't get merged in by June, we might ask you to temporarily close the PR while we migrate to GitLab. I'll have more details as that date gets closer.

**Comment by viraji** [comment]
> @viraji , thank you for your reply. Is it okay if I temporarily mark this as WIP (work in progress) in the title? I'll make those edits just so that we know.
> 
> FYI, there's a possibility that if this doesn't get merged in by June, we might ask you to temporarily close the PR while we migrate to GitLab. I'll have more details as that date gets closer.

Sure, thank you, Alyssa! Deadline by June is noted, and will try to finish before then.

**Comment by barbaricyawps** [comment]
@viraji , since you've stepped away from the project and this is still WIP, I'm going to close this pull request for now. Feel free to reopen it later when you return!

**Comment by viraji** [comment]
Sure, Thank you Alyssa.

Best Regards,
/Viraji.

**Pull request closed without merging**
